[project]
name = "agentic-architecture"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=1.11.0",
    "mcp[cli]>=1.6.0",
    "pyautogui>=0.9.54",
    "pywinauto>=0.6.9",
    "rich>=14.0.0",
]
